### PR TITLE
little cleanup

### PR DESCRIPTION
**Pull request by Jaccosf**
This is a fix for the 'no_vehicle_found' bug, even though there is a vehicle behind your towtruck.

### CODE REVIEW

**Comment by ZockerBoysHD** [comment]
this is acutally not a "fix" its just introducing a bug, where it could crash the whole script, cause its using "nil" as a vehicle, which obviously not exists. 
This check needs to be there.
you need to get OUT of your towtruck and stand at the end of it facing the vehicle you want to tow. not sit in it.

**Comment by Jaccosf** [comment]
If I'm not wrong, only the vehicleOnTowTruck should be checked on "nil" and for the targetVehicle it is only neccessary to check on the 0 value.

**Comment by ZockerBoysHD** [comment]
if it "never could be nil" the check wouldnt be a problem in the first place tho.  So if this check results in a problem, it actually gets set to "nil" which is not wanted for further processing of the vehicles.

Basicly your right, 0 and nil is the same. But for the code/game its acutally not so thats what the check is for. 
It is indeed "useless" but it can happen sometimes and these rare moments would crash the whole script. 

If you say you have problems with the target vehicle not being detected,  could you explain what ur doing and when this happened? If i test myself i dont get any problems :/ Work just like a charm

**Comment by Jaccosf** [comment]
I'll check this in a couple of minutes, but indeed if it couldn't be, it shouldn't be a problem. Anyways, it'll still make the code a little bit cleaner ;)

**Comment by ZockerBoysHD** [comment]
never ever revisited. Nothing changed, still same problems

**Pull request closed without merging**
